package com.smartretail.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * ============================================================
 * CategoryRequest DTO - Incoming Data for Create/Update Category
 * ============================================================
 *
 * WHY do we need DTOs?
 * ─────────────────────
 * The Model (Category.java) is our database entity.
 * The DTO is what we ACCEPT from the API client (Postman, React).
 *
 * We separate them because:
 * 1. The client should NOT send 'id', 'createdAt', 'updatedAt'
 *    (these are generated by the server, not the client)
 * 2. We can add validation rules (@NotBlank, @Size) here
 *    without polluting the Model class
 * 3. Different endpoints may need different views of the same data
 *
 * HOW VALIDATION WORKS:
 * ─────────────────────
 * When a controller method has @Valid @RequestBody CategoryRequest req,
 * Spring automatically validates it before the method runs.
 * If validation fails → GlobalExceptionHandler returns 400 Bad Request.
 *
 * Example valid request body (JSON):
 * {
 *   "name": "Electronics",
 *   "description": "All electronic items"
 * }
 * ============================================================
 */
public class CategoryRequest {

    /**
     * @NotBlank: Field cannot be null, empty, or whitespace-only.
     *   "Electronics" ✅  |  "" ❌  |  "   " ❌  |  null ❌
     *
     * @Size: Enforces character length constraints.
     *   min=2: At least 2 characters required.
     *   max=100: Maximum 100 characters allowed.
     */
    @NotBlank(message = "Category name is required")
    @Size(min = 2, max = 100, message = "Category name must be between 2 and 100 characters")
    private String name;

    @Size(max = 500, message = "Description cannot exceed 500 characters")
    private String description;

    // ─── Constructors ────────────────────────────────────────────────────────

    public CategoryRequest() {
    }

    public CategoryRequest(String name, String description) {
        this.name = name;
        this.description = description;
    }

    // ─── Getters ─────────────────────────────────────────────────────────────

    public String getName() {
        return name;
    }

    public String getDescription() {
        return description;
    }

    // ─── Setters ─────────────────────────────────────────────────────────────

    public void setName(String name) {
        this.name = name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    // ─── Builder ──────────────────────────────────────────────────────────────

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {
        private String name;
        private String description;

        private Builder() {
        }

        public Builder name(String name) {
            this.name = name;
            return this;
        }

        public Builder description(String description) {
            this.description = description;
            return this;
        }

        public CategoryRequest build() {
            return new CategoryRequest(name, description);
        }
    }
}
